# apiVersion: v1
# kind: Pod
# metadata:
  # name: getting-started
# spec:
  # containers:
  # - name: nginx
    # image: my-app-image
    
    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-new-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: my-app-image
          ports:
            - containerPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer    